// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PasswordManager.Api.Infrastructure;

#nullable disable

namespace PasswordManager.Api.Migrations
{
    [DbContext(typeof(PasswordManagerDbContext))]
    [Migration("20260228000000_AddUserAccounts")]
    partial class AddUserAccounts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PasswordManager.Api.Models.PasswordEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("PasswordEntries", (string)null);
                });

            modelBuilder.Entity("PasswordManager.Api.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d9f4954-0a14-4739-b0e0-6f6470d8c415"),
                            CreatedAtUtc = new DateTime(2026, 2, 27, 0, 0, 0, DateTimeKind.Utc),
                            Password = "Admin@123",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("2a0f7394-dbe4-4a65-9556-50d53fa4f141"),
                            CreatedAtUtc = new DateTime(2026, 2, 27, 0, 0, 0, DateTimeKind.Utc),
                            Password = "Gestor@123",
                            Username = "gestor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
